### ISSUE TITLE
Document - Tracking - Generator can be enhanced

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/csaf#115]
```json
        "generator": {
          "type": "object",
          "minProperties": 1,
          "properties": {
            "engine": {
              "type": "string",
              "minLength": 1
            },
            "date": {
              "type": "string",
              "format": "date-time"
            }
          }
        },
```

The above definition appears to be lacking value when we do not require the "engine" property to be set. A legit document could provide:
```json
        "generator": {
           "date": "2020-08-30"
          }
        },
```

Proposal:
> Enforce the presence of the engine property by adding required constraint and removing cardinality constraint:
>```json
>        "generator": {
>          "type": "object",
>          "required": [
>            "engine"
>          ],
>          "properties": {
>            "engine": {
>              "type": "string",
>              "minLength": 1
>            },
>            "date": {
>              "type": "string",
>              "format": "date-time"
>            }
>          }
>        },
>```

**Comment by sthagen** [comment]
@tschmidtb51  do you know a use case for date only payloads of the generator object?

**Comment by tschmidtb51** [comment]
I was thinking about one: If a company doesn't want to tell which engine it uses but wants to track when the file was generated. Usually, this can't be done by the "date" property within the "revision_history" since this should reflect the date when the revision was published.

However, I like the idea of making the property "engine" required.
