### ISSUE TITLE
Vulnerability Remediations - Configuration Change Mitigation

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#188]
This issue is meant to provide more details to the **Vulnerability Remediations - Configuration Change Mitigation** proposed in #185 by @wrideout.

---

## Vulnerability Remediations

**Configuration Change Mitigation**

In order to clearly convey configuration changes  which may provide a mitigatation for a vulnerability, we are suggesting a new type enum value for the remediation item type, named "configuration".  The "details" attribute of such an item would contain the configuration changes needed to mitigate the enclosing vulnerability.  For example:

```
"vulnerabilities": [
    {
      "references": [
        {
          "type": "self", 
          "url": "https://www.example.com/", 
          "summary": "CVE-0000-00000"
        }
      ], 
      "remediations": [ 
        {
          "type": "configuration", 
          "details": "some config which fixes the issue"
        }
      ],
...
```

**Comment by tschmidtb51** [comment]
@wrideout: If we introduce this type, I wonder: How do we know whether it is a
- `Workaround` (contains information about a configuration or specific deployment scenario that can be used to avoid exposure to the vulnerability. There may be none, one, or more workarounds available. This is typically the “first line of defense” against a new vulnerability before a mitigation or vendor fix has been issued or even discovered.)
- `Mitigation` (contains information about a configuration or deployment scenario that helps to reduce the risk of the vulnerability but that does not resolve the vulnerability on the affected product. Mitigations may include using devices or access controls external to the affected product. Mitigations may or may not be issued by the original author of the affected product, and they may or may not be officially sanctioned by the document producer.)
- `Vendor Fix` (contains information about an official fix that is issued by the original author of the affected product. Unless otherwise noted, it is assumed that this fix fully resolves the vulnerability.)

**Comment by wrideout** [comment]
The concern here is that when parsing the JSON there isn't a way (without looking into the actual contents of "detail") to know remediations item is a configuration change or something else.  This is applicable regardless of whether or not the type of the remediation item is "mitigation" or "workaround"-- I'm not sure that "vendor fix" is the same since that implies to me that a code change was made in a subsequent release to negate the vulnerability.

Given the constraints of the spec right now, I'n not sure how to answer your question right now without suggesting something obtuse like subsequent "mitigation-config" and "workaround-config" types.

I'm open to suggestions.

**Comment by tschmidtb51** [comment]
Maybe introducing the configuration section (see https://github.com/oasis-tcs/csaf/issues/186#issuecomment-786193004) could help here. This would enable us to reflect changes in the configuration (similar to the `product_tree`).

**Comment by wrideout** [comment]
Looking back at this again and comparing with the suggestions in #186-- I agree that a new configuration_tree property would solve this, with the understanding that the configuration_tree contents each has a new product_id for use with either "workaround" or "mitigation".

**Comment by wrideout** [comment]
Sorry for the delay-- I'm circling back on these 2.x issues so we can resolve them if possible.

Just so I'm clear: I think that the use of the configuration_tree property discussed [here](https://github.com/oasis-tcs/csaf/issues/186#issuecomment-786193004) would solve this (as I mentioned in my March 23 comment).  We would need to take this further and have the product_reference of the configuration_tree property referenced in the remediations property, with the type "mitigation" or even just "workaround".  Is that correct?

Do we need to take any further action on this issue?  It seems to me that this is moot until #186 has an agreed-upon way forward.

Again, apologies for the delay since I last participated on this.

**Comment by tschmidtb51** [comment]
> Just so I'm clear: I think that the use of the configuration_tree property discussed [here](https://github.com/oasis-tcs/csaf/issues/186#issuecomment-786193004) would solve this (as I mentioned in my March 23 comment). We would need to take this further and have the product_reference of the configuration_tree property referenced in the remediations property, with the type "mitigation" or even just "workaround". Is that correct?

I would say that product A with (the specific) config Y should form a new product B (with full product name and separate `product_id`). See also example in https://github.com/oasis-tcs/csaf/issues/291#issue-943789441. This makes the change smaller and easier to handle.

> Do we need to take any further action on this issue? It seems to me that this is moot until #186 has an agreed-upon way forward.

I would probably suggest to close this issue as we have the results from this discussion (`configuration_tree`) now tracked in #291.

**Comment by wrideout** [comment]
Sounds good to me!  Let's close this and pursue in #291.
