### ISSUE TITLE
Consider a set of proven values for maxima of string and array lengths

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/csaf#204]
When offering an API everyone and her dog will set practical limits for security reasons on the length of strings and arrays.

I suggest we do not leave the consumers and producers alone in the rainy situation of agreeing on some set of such limits.

can the members of the TC evaluate their corpus of existing advisories to determine at least a set of minimal sizes every process parsing csaf documents shall be able to handle?

I think this is an important contribution of the spec and the best place also.

I will suggest an amended safety, security, and data protection section regardless. But, if we can identify and agree on such a set of at least accept that set of limits for conforming roles / profiles it would be much easier to write the security aspect into the dedicated section (short, sweet, and clearly motivated).

Good idea, bad idea? Please give feedback - much appreciated.

**Comment by tschmidtb51** [comment]
Under the impulse of the moment, I fear that a limitation in length of strings might contradict our intention of detailed descriptions, notes,...

Let me give 2 examples why I think it is really hard to decide:

- `document/publisher/name` (for the sake of simplicity just assuming that #201 comes through): Is 50 enough? Definitely not (since we have a longer name - even without mention the section)...
- `branches[]`: How many items should we allow here? A company could easily have >50000 products. If there is a vulnerability which affects a core component you have a lot of products to describe in a advisory...

However, I agree that people will implement certain limitations - and we should provide the guidance. For example, as a developer I would start looking into the recursion of `branches_t`. I think a minimal size of 25 should be enough.

We should be aware that if we set such minimal sizes anyone can only produce advisories within that boundaries to make sure that the consumer are able to process the documents.

Nevertheless, I'm happy to define such boundaries if they exist. I'm open to the TC's discussion.

**Comment by tschmidtb51** [comment]
Maybe we should add that to the agenda of the next meeting?

**Comment by santosomar** [comment]
Considered done. It will be added to the agenda.

**Comment by sthagen** [comment]
Added the email tag for consistency 🙈

**Comment by sthagen** [comment]
To help maintain the focus of the discussion: I do not believe finding a set of smallest useful maxima for interoperability is easy, but if we do not even try, the communities have to take over, which I think is not a good message.

I imagine that aggregators might want to use that format to, and there we may have astronomical collections. But, for interchange there has to be a way 🚀

**Comment by sthagen** [comment]
We can try to start from the amount of bytes accepted per POST in typical REST API settings, and also from file size info by those active in the field in case transport is per rsync, sftp, or message queues.

* Would 50 Megabytes of bytes on the wire or on disk be a meaningful limit (to expect acceptance with every participant conforming to the standard) in the spec? Adding that when  larger the server may accept language.
* I also consider triaging broad categories  for „majorer, minorer, approcher“ meaningful limits in case of strings.

Another approach for example separating title like  from text fields providing book like content.

* Would a title wire size of 4096 kilobytes be enough?
* Would a main body like text field with 1 Megabyte size be enough?

similar @tschmidtb51 reasoning w.r.t. the depth of the recursive structures.

With arrays (remember scope is external zero-trust limits) we could also set quite high limits for conformance.

Then one could enforce consumers, any recipient role we suggest conformance clauses for to at least accept these sizes.

These size constraints do not hinder any community from using larger sizes within given the tool configurations and machinery support but instead articulate a minimum taxonomy that has to be afforded from every conforming participant (conforming with CSaF 2.0).

So to clarify: Not aiming in adding the max to the schema but instead to the prose and maybe provide a conforming openapi sample with limits set that allow these sizes where possible. Recursion depth may be a business rule not enforceable within schema or openapi.

**Comment by mprpic** [comment]
I am indifferent about any max limits on the data, but I'll note that the CVE JSON schema maintained by MITRE also recently put in max limits for most fields:

https://github.com/CVEProject/cve-schema/pull/13/files

Their use case is that the underlying database (MongoDB) has a max limit of 16MB for one document, and the schema allows submitting supporting media as base64-encoded input (so even images or audio files), so it is necessary to put in some max limits to prevent issues with saving very large CVE JSON documents in their service's database.

**Comment by tschmidtb51** [comment]
I provide a suggestion for this in #256. Please review.
