### ISSUE TITLE
Vendor ID issued by FIRST

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#267]
In CVRF there was a informative comment:
> At the time of this writing, OID issuance by FIRST is still a work in progress, thus some samples are provided below, that use OIDs from other standard MIBs.

Can someone confirm that FIRST now issues the OIDs? Or do we need to change something? E.g. refer to [OID](http://oid-info.com)

**Comment by tolim** [comment]
I just had a discussion with some of the relevant colleagues in FIRST: 
FIRST currently does not issue any OIDs for vendors. Their PSIRT SIG is working on a vendor contact card, but nothing is available right now. I would suggest to leave out the informative comment to avoid confusion. When something is available in the future, let's include it in an incremental update of CSAF.

**Comment by tschmidtb51** [comment]
I would then suggest to remove the vendor_id completely or replace it with a publisher url / namespace. The latter would provide the namespace for `/document/tracking/id` and will solve the problem that these IDs are only organizational unique.

Thoughts?

**Comment by tschmidtb51** [comment]
@mprpic, @santosomar: Are you aware of anyone using the field `vendor_id`?

**Comment by santosomar** [comment]
I am not aware of anyone using the `vendor_id` field.

**Comment by mprpic** [comment]
> @mprpic, @santosomar: Are you aware of anyone using the field `vendor_id`?

I am not. This is the first time I'm hearing about OID.

**Comment by tschmidtb51** [comment]
I added a [PR](#274) as suggestion for this problem.

**Comment by sthagen** [comment]
From discussions of the changes in the PR #274 I perceive that the replacement field for `vendor_id` might attract additional and unfortunately diverging semantics. I understand the publisher namespace as a simple anchor to complete the local unique identifier into an ordered pair of identifiers that is globally unique. Others seem to want to use that same publisher namespace value as directly dereferenceable key identifier for key distribution and signature validation of the document itself.

I propose we discourage that second strong coupling to signatures at least for version 2.0 and focus on the main purpose of the publisher namespace. Especially, because (1) that addition fixes a bluff from CVRF 1.2 and earlier (promising semantics that were never practically useful) and (2) as adding the new namespace field IMO brings CSAF closer to typical SBOM formats like CycloneDX and SPDX when it comes to attribution / source identification.
