### ISSUE TITLE
CPE regex

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-tcs/csaf#91]
The schema is missing a full regular expression to enforce CPE syntax. This issue should track suggestions and develop one / check existing ones.
A starting point could be figures 6-1 to 6-3 from [Common Platform Enumeration: Naming Specification Version 2.3](https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir7695.pdf).

**Comment by sthagen** [comment]
We might profit from harvesting some CPR samples in the wild. I would start with the very generous regex (case insensitive):
```javascript
          "pattern": "^(?i)cpe:(/|\\d+\\.\\d+)[^:]*:?[^:]*:?[^:]*:?[^:]*:?[^:]*:?[^:]*:?[^:]*$",
```
The above pattern supports both serialization forms of CPE WFN: URI schema and String Format Binding.

Two additional actions jump into my line of sight (besides resolvng or updating the `$comment` member value):

1. We should update the `minLen` value to the minimum length our final regex will let pass
2. We should look out for validators that choke on the case insensitive "prefix" ...

**Comment by tolim** [comment]
A few comments, as I needed to get into the topic myself:

1. We need to rely on a reduced syntax as defined in Javascript (ECMA-262, https://json-schema.org/understanding-json-schema/reference/regular_expressions.html), so your prefix should not be used.
2. Unfortunately CVRF 1.2 does not define which naming scheme is allowed, so we would need to cover all three: 
    - WFN (`wfn:[part="a",vendor="microsoft",product="internet_explorer",
version="8\.0\.6001",update="beta"]`)
     - URI binding (`cpe:/a:microsoft:internet_explorer:8.0.6001:beta`), or 
     - formatted string binding (`cpe:2.3:a:microsoft:internet_explorer:8.0.6001:beta:*:*:*:*:*:*`)
3. The suggested pattern does not match the formatted string binding example above, as it has more `:` as expected,
4. It gives almost complete freedom on WFN as no `:` are contained in this naming scheme.
5. It is very performance-intensive due to the many possible branches during matching.
6. MITRE already gives us an "official" regex for formatted string binding (https://csrc.nist.gov/schema/cpe/2.3/cpe-naming_2.3.xsd): 
```
cpe:2\.3:[aho\*\-](:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#$$%&'\(\)\+,/:;<=>@\[\]\^`\{\|}~]))+(\?*|\*?))|[\*\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\*\-]))(:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#$$%&'\(\)\+,/:;<=>@\[\]\^`\{\|}~]))+(\?*|\*?))|[\*\-])){4}
```

To correct issues 1) and 3), I'll throw in the following proposal (escaping still needs to be fixed for the json schema, but this is better debuggable):
```
^[Cc][Pp][Ee]:(\/|\d+\.\d+)[^:]*(:?[^:]*){0,11}$
```

And I will keep searching for a good regex, it has to be out there somewhere.

**Comment by sthagen** [comment]
Maybe we should keep three distinct patterns?

Going wild - kind of - why should we bother removing empty arrays and strings, when we allow in this case (cpe) a single element to carry payloads to be validated against coming from three distinct grammars/forms? 

I suggest, we rather: 

* make this element an array and 
  * add `anyOf` objects with single and clear properties with
    * the keys inside (`wfn`, `uri`, and `bind`)

Then, we can declare dedicated grammar representing patterns in clearly defined situations (triggered by the key. 

A producer should be able to not only provide some cpe value, but in addition declare what grammar the value follows

A consumer should enjoy the clarity and the reduced complexity of the task to validate agains matching acceptance rules.

**Comment by sthagen** [comment]
Another strategy would be, to accept only one field. Either the preferred CPE 2.3 `bind` serialization or to ease the consumers the `wfn` Per an external JSON schema (as we did for the CVSS _version zoo_ (three times).

**Comment by tolim** [comment]
> Another strategy would be, to accept only one field. Either the preferred CPE 2.3 `bind` serialization or to ease the consumers the `wfn` Per an external JSON schema - as we did for the CVSS _version zoo_ (three times).

I would prefer this suggestion. Only allow the commonly used 'URI binding' serialization, as this keeps complexity of the schema and for parsers down.

**Comment by tolim** [comment]
Just one additional note from our discussion yesterday: as it is possible to easily convert between the CPE 2.3 naming schemes, automatic conversion of CVRF 1.2 to CSAF 2.0 is still possible, even if we only allow one naming scheme like 'formatted string binding' in CSAF 2.0.

**Comment by sthagen** [comment]
# TL;DR:
I think we should go with the full WFN (I am willing to sketch such a JSON object representing a WFN myself)

## Details
In the following when I mention CVEs - I do not think of them as security advisories but consider the shared risk of identifying products and relating those ids (CPEs) to vulnerabilities or mitigations.

### Background
I continued to think about this important dimension of a security advisory. There is interesting literature [Luis Alberto Benthin Sanguino, Rafael Uetz: "Software Vulnerability Analysis Using CPE and CVE"](https://arxiv.org/pdf/1705.05347.pdf) (approx. 3 years old) that highlights the fact, that on the consumer side any practical algorithm to best find if a product is impacted is only approximate and iterative to avoid positive and negative false matches. The authors have some python code within their [IVA](https://github.com/fkie-cad/iva) project at github that implements the algorithms for reaping CPE matches from CVEs.

### The Problem
In essence this is due to the fact, that CVEs name non-existing CPEs (the products exist) and that CVEs seem to use serializations that e.g. "coerce" version and "version attributes" into one field like 1.2.3 vs. 1.2.3_beta4 where CPE dictionary at MITRE has them split.

### Proposal
Given that we offer the full CVSS structures (deserialized) I lean more towards using a JSON object to model the documented WFN form of CPE v2.3 as elements in our CSAF advisory JSON texts and no serialization like BIND or URI syntax.

**Comment by sthagen** [comment]
While discussion is ongoing, we have the IMO interesting situation, that some Software Bill of Materials (SBOM) related specs [CycloneDX JSON](https://cyclonedx.org/schema/bom-1.2.schema.json) accept CPE and other such identifier domain values as `^.*$` regexes equivalent to 0 or more characters in their JSON schema ... (which eases the producer but renders nearly no value to consumers expecting actionable (SIEM) content) while other SBOM like specs like SPDX ([CPE22](https://spdx.github.io/spdx-spec/appendix-VI-external-repository-identifiers/#cpe22type) & [CPE23](https://spdx.github.io/spdx-spec/appendix-VI-external-repository-identifiers/#cpe23type)) and even [CycloneDX in XML variant](https://cyclonedx.org/docs/1.2/#type_cpe) quite detailed REGEXes:

> SPDX CPE 2.2 Locator Format:
> ```
> [c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6}
> ```
> SPDX CPE 2.2 Contextual Example:
> ```
> cpe:/o:canonical:ubuntu_linux:10.04:-:lts
> ```
> 
> SPDX CPE 2.3 Locator Format:
> ```
> cpe:2\.3:[aho\*\­]
> (:(((\?*|\*?)([a­zA­Z0­9\­\._]|(\\[\\\*\?!
> "#$$%&'\(\)\+,/:;<=>@\[\]\^`\{\|}~])
> )+(\?*|\*?))|[\*\­])){5}
> (:(([a­zA­Z]{2,3}(­([a­zA­Z]{2}|[0­9]{3
> }))?)|[\*\­]))
> (:(((\?*|\*?)([a­zA­Z0­9\­\._]|(\\[\\\*\?!
> "#$$%&'\(\)\+,/:;<=>@\[\]\^`\{\|}~])
> )+(\?*|\*?))|[\*\­])){4}
> ```
> SPDX CPE 2.3 Contextual Example:
> ```
> cpe:2.3:o:canonical:ubuntu_linux:10.04:­:lts:*:*:*:*:*
> ```
> 
> Cyclone DX XML CPE (same field supports CPE 2.2 and 2.3 payload 🤔 )
> ```xml
> pattern = ([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6})|(cpe:2\.3:[aho\*\-](:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#$$%&'\(\)\+,/:;<=>@\[\]\^`\{\|}~]))+(\?*|\*?))|[\*\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\*\-]))(:(((\?*|\*?)([a-zA-Z0-9\-\._]|(\\[\\\*\?!"#$$%&'\(\)\+,/:;<=>@\[\]\^`\{\|}~]))+(\?*|\*?))|[\*\-])){4})
> ```

**Comment by sthagen** [comment]
@santosomar, @tschmidtb51, and @tolim I hereby propose to close this issue as 
* I did not notice discussions anymore on that topic and 
* to my understanding our current constraints on CPE seem to be OK for what CPE is able to offer (surprising high false both positive and negative errors in matching vulnerabilities to products per CPE).

**Comment by tschmidtb51** [comment]
@sthagen I just provided a PR (#324) for that.
